/* CRIAÇÃO DA CONSTANTE QUE REPRESENTA O NOME DO BANCO DE DADOS*/

const database = 'BD3-AULA';

/* CRIAÇÃO DA CONSTANTE QUE REPRESENTA O NOME DA COLEÇÃO DE AQRQUIVOS*/
const collection = 'LIVRARIA';

/* DEFINE O BANCO DE DADOS QUE SERA UTILIZADO, CASO NÃO EXISTA SERA CRIADO */
use(database);

/* CRIA UMA COLEÇÃO DE DADOS */
db.createCollection(collection);
