/* CRIAÇÃO DA CONSTANTE QUE REPRESENTA O NOME DO BANCO DE DADOS*/
const database = 'BD3-AULA';

/* CRIAÇÃO DA CONSTANTE QUE REPRESENTA O NOME DA COLEÇÃO DE AQRQUIVOS*/
const collection = 'LIVRARIA';

/* DEFINE O BANCO DE DADOS QUE SERA UTILIZADO, CASO NÃO EXISTA SERA CRIADO */
use(database);

/* SELECIONA OS DADOS DE TODOS OS ARQUIVOS SEM CRITÉRIO*/
db['LIVRARIA'].find();

/* SELECIONA ARQUIVOS COM DADOS DE ACORDO COM A CATEGORIA DEFINIDA*/
//db['LIVRARIA'].find({"categoria":"Fantasia Heroica"},{"_id":0, "codigo":0, "descricao":0});